### ISSUE TITLE
In package.json add scripts section

### ISSUE THREAD

**Issue by yvesh** [joomla-projects/gsoc16_js-unit-tests#32]
@Ruchiranga reading the README.md from you again. Instead of the part where you suggest installing karma etc. in global namespace to easier run it, i thought on the following:

In your package.json you normally set up scripts, to be executed by npm (like npm start). You already made a sample for that in the file!

Please try adjusting the package.json to run karma that way, for example:

```
"scripts": {
    "test": "node_modules/karma/bin/karma start ../../karma.conf.js --single-run"
},
```

Then people just can use npm test

**Comment by Ruchiranga** [comment]
The command needs to have the word 'node' in front, doesn't it?
"scripts": {
    "test": "node node_modules/karma/bin/karma start ../../karma.conf.js --single-run"
}

**Comment by yvesh** [comment]
Done with #29
